# Copyright (c) 2025, Huawei Technologies Co., Ltd. All rights reserved.
from enum import IntEnum


class WorkerStatus(IntEnum):
    """Worker status enumeration"""

    INIT = 0
    NORMAL = 1
    ABNORMAL = 2  # Self-reported fault
    FAULT = 3  # Heartbeat timeout, marked as fault by Controller
    PAUSE = 4  # Entered wait state (received PAUSE message)
    STOPPED = 5


class MsgType(IntEnum):
    """Message type enumeration"""

    HEARTBEAT = 1
    HEARTBEAT_ACK = 2
    REGISTER = 3
    REGISTER_ACK = 4
    REGISTER_REPLICA_GROUP = 5
    REGISTER_REPLICA_GROUP_ACK = 6
    DUMP_REQUEST = 7
    DUMP_RESPONSE = 8
    EXCEPTION = 9
    TRIGGER_DUMP = 11
    TRIGGER_DUMP_ACK = 12
    WAIT_RELEASE = 13
    EXIT = 18


MSG_TYPE_HEARTBEAT = MsgType.HEARTBEAT
MSG_TYPE_HEARTBEAT_ACK = MsgType.HEARTBEAT_ACK
MSG_TYPE_REGISTER = MsgType.REGISTER
MSG_TYPE_REGISTER_ACK = MsgType.REGISTER_ACK
MSG_TYPE_REGISTER_REPLICA_GROUP = MsgType.REGISTER_REPLICA_GROUP
MSG_TYPE_REGISTER_REPLICA_GROUP_ACK = MsgType.REGISTER_REPLICA_GROUP_ACK
MSG_TYPE_DUMP_REQUEST = MsgType.DUMP_REQUEST
MSG_TYPE_DUMP_RESPONSE = MsgType.DUMP_RESPONSE
MSG_TYPE_EXCEPTION = MsgType.EXCEPTION
MSG_TYPE_TRIGGER_DUMP = MsgType.TRIGGER_DUMP
MSG_TYPE_TRIGGER_DUMP_ACK = MsgType.TRIGGER_DUMP_ACK
MSG_TYPE_WAIT_RELEASE = MsgType.WAIT_RELEASE
MSG_TYPE_EXIT = MsgType.EXIT


DEFAULT_SERVER_IP = '0.0.0.0'
DEFAULT_SERVER_PORT = 29500
DEFAULT_HEARTBEAT_INTERVAL_MS = 1000
DEFAULT_HEARTBEAT_TIMEOUT_MS = 3000
DEFAULT_MAX_MISSED_COUNT = 3
DEFAULT_DUMP_DIR = 'ttp_dump'
DEFAULT_DUMP_TIMEOUT_SECONDS = 60
DEFAULT_WAIT_DUMP_FILE_TIMEOUT = 60
MAX_DUMP_CKPT_TO_KEEP = 1
