# Copyright (c) 2025, Huawei Technologies Co., Ltd. All rights reserved.
from argparse import ArgumentParser

from mindspeed.features_manager.feature import MindSpeedFeature

from mindspeed_llm.training.swanlab_adapter import SWANLAB_MODES


class SwanLabFeature(MindSpeedFeature):

    def __init__(self):
        super(SwanLabFeature, self).__init__(feature_name="swanlab", optimization_level=0)

    def register_args(self, parser: ArgumentParser):
        group = parser.add_argument_group(title=self.feature_name)
        group.add_argument('--swanlab-project', type=str, default='',
                            help='The swanlab project name. Ignore swanlab by default.')
        group.add_argument('--swanlab-exp-name', type=str, default='',
                            help='The swanlab experiment name. Generated by swanlab when left empty.')
        group.add_argument('--swanlab-save-dir', type=str, default='',
                            help='Path to save the swanlab results locally. '
                                 'Defaults to a "swanlab" folder under --save.')
        group.add_argument('--swanlab-mode', type=str, default='offline', choices=SWANLAB_MODES,
                            help='"online" syncs to swanlab.cn and needs both network access and an '
                                 'API key from SWANLAB_API_KEY, "local" keeps data on disk for '
                                 '"swanlab watch", "offline" keeps it for a later "swanlab sync", '
                                 '"disabled" turns tracking off. Defaults to offline because compute '
                                 'nodes are usually air-gapped.')

    def validate_args(self, args):
        super().validate_args(args)

        ## zhh: 两者共用 _GLOBAL_WANDB_WRITER 这一个槽位, 同时开只会有一个生效, 早报错
        if getattr(args, 'swanlab_project', '') and getattr(args, 'wandb_project', ''):
            raise AssertionError('--swanlab-project and --wandb-project both write to the same '
                                 'writer slot, please enable only one of them')

    def register_patches(self, patch_manager, args):
        from mindspeed_llm.training.swanlab_adapter import set_wandb_writer_wrapper
        patch_manager.register_patch('megatron.training.global_vars._set_wandb_writer',
                                      set_wandb_writer_wrapper)

        if getattr(args, 'swanlab_project', ''):
            from mindspeed_llm.training.swanlab_adapter import (
                swanlab_noop_on_load_checkpoint_success,
                swanlab_noop_on_save_checkpoint_success,
            )
            patch_manager.register_patch('megatron.training.wandb_utils.on_save_checkpoint_success',
                                          swanlab_noop_on_save_checkpoint_success)
            patch_manager.register_patch('megatron.training.wandb_utils.on_load_checkpoint_success',
                                          swanlab_noop_on_load_checkpoint_success)
